name = "OMOPCDMPathways"
uuid = "413b2380-0cee-426e-ad22-874d5a2600da"
authors = ["Jay-sanjay <landgejay124@gmail.com> and contributors"]
version = "0.0.1"

[deps]
FunSQL = "cf6cc811-59f4-4a10-b258-a8547a8f6407"

[compat]
DocumenterVitepress = "0.0.19"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
